version: "3.7"
services:
  app:
    build: ./
    command: rails s -p 8000
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file:
      .env_app
    depends_on:
      - db
    network:
      - internal
  db:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      .env_db
    network:
      - internal
networks:
  default:
    - internal
