default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  user:  <%= ENV.fetch('DB_USER') %>
  database: <%= ENV.fetch('DB_DATABASE') %>
  host: <%= ENV.fetch('DB_HOST') %>
  port: <%= ENV.fetch('DB_PORT') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: <%= ENV.fetch('DB_DATABASE') %>
  host: <%= ENV.fetch('DB_HOST') %>
  port: <%= ENV.fetch('DB_PORT') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
