default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: ENV['DB_DATABASE']
  host: ENV['DB_HOST']
  port: ENV['DB_PORT']
  password: ENV['DB_PASSWORD']

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: ENV['DB_DATABASE']
  host: ENV['DB_HOST']
  port: ENV['DB_PORT']
  password: ENV['DB_PASSWORD']
